<script type="text/javascript" src="assets/libs/jquery.min.js"></script>
<script type="text/javascript" src="assets/libs/jquery.migrate.min.js"></script>
<script type="text/javascript" src="assets/libs/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="assets/js/platform.js"></script>
<script type="text/javascript" src="assets/libs/jquery.smooth-scroll.min.js"></script>
<script type="text/javascript" src="assets/libs/jquery.back-to-top.min.js"></script>
<script type="text/javascript" src="assets/libs/scrollbar/jquery.scrollbar.min.js"></script>
<script type="text/javascript" src="assets/libs/swiper/swiper.jquery.min.js"></script>
<script type="text/javascript" src="assets/libs/masonry/jquery.masonry.pkgd.min.js"></script>
<script type="text/javascript" src="assets/libs/masonry/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="assets/libs/jquery.equal-height.min.js"></script>
<script type="text/javascript" src="assets/libs/jquery.parallax.min.js"></script>
<script type="text/javascript" src="assets/libs/jquery.wow.min.js"></script>
<script type="text/javascript" src="assets/libs/global.min.js"></script>
<script type="text/javascript" src="assets/libs/components/header-sticky.js"></script>
<script type="text/javascript" src="assets/libs/components/scrollbar.min.js"></script>
<script type="text/javascript" src="assets/libs/components/swiper.min.js"></script>
<script type="text/javascript" src="assets/libs/components/masonry.min.js"></script>
<script type="text/javascript" src="assets/libs/components/equal-height.min.js"></script>
<script type="text/javascript" src="assets/libs/components/parallax.min.js"></script>
<script type="text/javascript" src="assets/libs/components/wow.min.js"></script>